# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0002_0_2_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_pub_key', models.SlugField(max_length=32, unique=True,
                    help_text='Unique public identifier for the API key')),
                ('api_priv_key', models.CharField(max_length=128,
                    help_text='Private portion of the API key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
