# Generated by Django 4.2.22 on 2025-08-22 17:12

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_auto_20231006_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_verification_required',
            field=models.BooleanField(default=False, help_text='Auth requires email verification every time'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_verification_required',
            field=models.BooleanField(default=False, help_text='Auth requires phone verification every time'),
        ),
    ]
